apiVersion: apps/v1
kind: Deployment
metadata:
  name: soatdb-deployment
spec:
  template:
    metadata:
      name: soatdb
      labels:
        app: soatdb
    spec:
      containers:
      - name: soatdb
        image: mysql:8.0.33
        ports:
          - containerPort: 3306
        envFrom:
          - configMapRef:
              name: soatdb-configmap
        volumeMounts:
          - name: shared-data
            mountPath: /var/lib/mysql
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: soatdb-pvc
  selector:
    matchLabels:
      app: soatdb
