apiVersion: v1
kind: PersistentVolume
metadata:
  name: soatdb-pv
  labels:
    name: soatdb-pv
spec:
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/ntopus/Documentos/estudos/fiap/postech-soat/database
